apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-violations
  namespace: argocd
  labels:
    app.kubernetes.io/name: test-violations
    app.kubernetes.io/part-of: remediator-testing
    environment: test
spec:
  project: default
  source:
    repoURL: https://github.com/Anujramola1999/project-remediator-agent.git
    path: test-workloads
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=true
      - Force=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m

  revisionHistoryLimit: 10
