apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-test
  namespace: application
  labels:
    app: privileged-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privileged-test
  template:
    metadata:
      labels:
        app: privileged-test
    spec:
      containers:
      - name: privileged-container
        image: nginx:1.20
        securityContext:
          privileged: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 80