apiVersion: apps/v1
kind: Deployment
metadata:
  name: seccomp-test
  namespace: application
  labels:
    app: seccomp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seccomp-test
  template:
    metadata:
      labels:
        app: seccomp-test
    spec:
      containers:
      - name: seccomp-container
        image: nginx:1.20
        securityContext:
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 80
